name: Build Assembly
description: Action de Build de Assembly
author: Silask1

inputs:
  version:
    required: false
    type: string
    description: Número da Versão
  build:
    required: false
    type: string
    description: Tipo do Build (beta, rc, release)
  csproj:
    required: false
    type: string
    description: Arquivo de Build Microsoft
  nupkg:
    required: false
    type: string
    description: Path pacote nuget
  username:
    required: false
    type: string
    description: Username Nuget
  token:
    required: false
    type: string
    description: Token Nuget
  
runs:
  using: 'node12'
  main: 'dist/index.js'