name: Build Assembly
description: Action de Build de Assembly
author: Silask1

inputs:
  versao-major:
    required: false
    type: string
    description: Quando fizer mudanças incompatíveis na API
  # versao-minor:
  #   required: false
  #   type: string
  #   description: Quando adicionar funcionalidades mantendo compatibilidade
  versao-patch:
    required: false
    type: string
    description: Quando corrigir falhas mantendo compatibilidade
  versao-patch-sufixo:
    required: false
    type: string
    description: Sufixo do build (beta, rc)
  config:
    required: false
    type: string
    description: Tipo do Build (Beta, Rc, Release)
  csproj:
    required: false
    type: string
    description: Arquivo de Build Microsoft
  nupkg:
    required: false
    type: string
    description: Path pacote nuget
  username:
    required: false
    type: string
    description: Username Nuget
  token:
    required: false
    type: string
    description: Token Nuget
  version-code:
    required: false
    type: string
    description: código de autenticação do request no azure
  version-token:
    required: false
    type: string
    description: token de autenticação cosmoDb no Azure
  version-endpoint:
    required: false
    type: string
    description: endereço do cosmoDb Azure
  name-package:
    required: false
    type: string
    description: nome do pacote ou serviço para gerar versionamento

runs:
  using: 'node16'
  main: 'dist/index.js'