name: Build Assembly
description: Action de Build de Assembly
author: Silask1

inputs:
  build:
    required: true
    type: string
    description: Tipo do Build (beta, rc, release)
  
runs:
  using: 'node12'
  main: 'dist/main.js'