name: Build Assembly
description: Action de Build de Assembly
author: Silask1

inputs:
  versao-major:
    required: false
    type: string
    description: Quando fizer mudanças incompatíveis na API
  versao-minor:
    required: false
    type: string
    description: Quando adicionar funcionalidades mantendo compatibilidade
  versao-patch:
    required: false
    type: string
    description: Quando corrigir falhas mantendo compatibilidade
  versao-patch-sufixo:
    required: false
    type: string
    description: Sufixo do build (beta, rc)
  config:
    required: false
    type: string
    description: Tipo do Build (Beta, Rc, Release)
  csproj:
    required: false
    type: string
    description: Arquivo de Build Microsoft
  nupkg:
    required: false
    type: string
    description: Path pacote nuget
  username:
    required: false
    type: string
    description: Username Nuget
  token:
    required: false
    type: string
    description: Token Nuget
  
runs:
  using: 'node16'
  main: 'dist/index.js'