name: Build API
description: Action de Build API
author: Silask1

inputs:
  hub:
    required: false
    type: string
  projeto:
    required: false
    type: string
  config:
    required: false
    type: string
  versao-major:
    required: false
    type: string
  versao-minor:
    required: false
    type: string
  versao-patch:
    required: false
    type: string
  versao-patch-sufixo:
    required: false
    type: string
  docker_username:
    required: false
    type: string
  docker_token:
    required: false
    type: string

runs:
  using: 'node12'
  main: 'dist/index.js'