name: Build API
description: Action de Build API
author: Silask1

inputs:
  api_dominio:
    required: false
    type: string
  api:
    required: false
    type: string
  stack:
    required: false
    type: string
  config:
    required: false
    type: string
  versao:
    required: false
    type: string
  versao_number:
    required: false
    type: string
  ssh_host:
    required: false
    type: string
  ssh_port:
    required: false
    default: 22
  ssh_username:
    required: false
    type: string
  ssh_password:
    required: false
    type: string
  docker_username:
    required: false
    type: string
  docker_token:
    required: false
    type: string

runs:
  using: 'node12'
  main: 'dist/index.js'