name: Deploy API
description: Action para Subir deploy no Docker
author: Silask1

inputs:
  host:
    required: false
    type: string
    description: Host Server
  port:
    required: false
    type: string
    description: Port SSH
  username:
    required: false
    type: string
    description: Username SSH
  password:
    required: false
    type: string
    description: Password SSH
  key:
    required: false
    type: string
    description: Private Key SSH
  stack:
    required: false
    type: string
    description: Nome da Stack

runs:
  using: 'node12'
  main: 'dist/index.js'