name: Deploy API
description: Action para Subir deploy no Docker
author: Silask1

inputs:
  host:
    required: false
    type: string
    description: Host Server
  port:
    required: false
    type: string
    description: Port SSH
  username:
    required: false
    type: string
    description: Username SSH
  password:
    required: false
    type: string
    description: Password SSH
  key:
    required: false
    type: string
    description: Private Key SSH
  stack:
    required: false
    type: string
    description: Nome da Stack
  config:
    required: false
    type: string
    description: Tipo de build (Beta, Rc, Release)
  versao-major:
    required: false
    type: string
    description: Quando fizer mudanças incompatíveis na API
  versao-minor:
    required: false
    type: string
    description: Quando adicionar funcionalidades mantendo compatibilidade
  versao-patch:
    required: false
    type: string
    description: Quando corrigir falhas mantendo compatibilidade
  versao-patch-sufixo:
    required: false
    type: string
    description: Sufixo do build (beta, rc)
  latest:
    required: false
    type: boolean
    description: Informa se a versão a ser gerada é latest (Produção)
    default: false
  path:
    required: false
    type: string

runs:
  using: 'node20'
  main: 'dist/index.js'