name: Build das Actions TLV7

on:
  push:
    branches: 
      - main
    paths: 
      - ./deploy/**
      
jobs:
  build_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build action deploy
        run: npm run build