name: Build das Actions TLV7 (build-api)

on:
  push:
    branches: 
      - main
    paths: 
      - build-api/src/**
      
jobs:
  build_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build action build-api
        run: npm run build
